### PR TITLE
Use std::launder instead of getHandler().

### PR DESCRIPTION
**Pull request by BengtGustafsson**

### CODE REVIEW

**Comment by jbcoe** [comment]
Watching this PR arrive and see tests passing in real time was rather satisfying!

**Review by jbcoe — APPROVED** [review]
I'm no expert on launder but this LGTM.

**Review by jbcoe — APPROVED** [review]
I'm no expert on launder but LGTM

**Comment by BengtGustafsson** [comment]
As I understand it launder does exactly this, prevents the compiler from assuming that a by value object has not been inplace-newed with some other type.

An alternative would be a pointer table. Maybe I will make a new version without SBO but using a pointer table.

**Comment by Twon** [comment]
> As I understand it launder does exactly this, prevents the compiler from assuming that a by value object has not been inplace-newed with some other type.
> 
> An alternative would be a pointer table. Maybe I will make a new version without SBO but using a pointer table.

Interesting, I think this explains why the `getHandler` approach was not completely successful. What I saw when debugging the GCC build in GDB, was that the vtable pointer was correctly set, but in some instances the compiler could still assume by value access.

**Pull request merged**
